# add github location with credential 
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
#        git:
#          uri: classpath:/config
  profiles:
     active: native

server:
  port: 8888
  
#security:
#  user:
#    password: password