server:
#  context-path: /gateway
  port: 8001
  
zuul:
  ignoredServices: '*'
  host:
    connect-timeout-millis: 20000
    socket-timeout-millis: 20000
  
  routes:
    resource2:
        path: /rest/**
        url: http://localhost:8002/rest/
#    clinet1:
#        path: /client1/**
#        serviceId: client1
#        stripPrefix: false
#        sensitiveHeaders:
        